name: guillotina_amqp

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the repository first
      - uses: actions/checkout@v4

      # Setup the python version
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Linters and typing
      - name: Pre-checks
        run: |
          # Install
          pip install flake8 black==25.1.0 mypy mypy_zope

          # Run commands
          flake8 guillotina_amqp --config=setup.cfg
          black --check --verbose guillotina_amqp
          mypy -p guillotina_amqp --ignore-missing-imports

      # Run tests
      - name: Run tests
        run: |
          # Install guillotina from onna fork
          pip install git+https://github.com/onna/guillotina.git

          # Install package with test dependencies
          pip install -e .[test]

          # Run tests
          RABBITMQ=localhost:5672 pytest --tb=native -v --capture=no guillotina_amqp --cov=guillotina_amqp --cov-report xml --cov-append guillotina_amqp

          # install codecov library
          pip install codecov

          codecov --url="https://open-coverage.org/api" --token=14396163 --slug=guillotinaweb/guillotina_amqp
